name: devsdocs_reusable_tools
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  crypto:
  dio:
  jiffy:
  path:
  uuid:

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
