name: devsdocs_reusable_tools
description: Personal Reusable Tools. Feel free to modify.
version: 1.0.2
repository: https://github.com/devsdocs/dart_reusable_tools

environment:
  sdk: ^3.0.6

dependencies:
  crypto:
  dio:
  english_words_300k:
  jiffy:
  path:
  uuid:

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0